### ISSUE TITLE
docker内报错

### ISSUE THREAD

**Issue by saxon17** [xsren/wx_taobao_fanli#30]
File "/app/libs/wx_bot.py", line 145, in run
    itchat.auto_login(enableCmdQR=2, hotReload=True)
  File "/Devops/py3env/lib/python3.5/site-packages/itchat/components/register.py", line 29, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback):
  File "/Devops/py3env/lib/python3.5/site-packages/itchat/components/hotreload.py", line 54, in load_login_status
    self.loginInfo['User'] = templates.User(self.loginInfo['User'])
KeyError: 'User'
(py3env) root@32894c963ac2

**Comment by saxon17** [comment]
No uins in 51 message

**Comment by saxon17** [comment]
2018-11-14 10:12:05,591 get_tk_link[line:306] [WARNING]: error:'data',trace:Traceback (most recent call last):
  File "/app/libs/alimama.py", line 300, in get_tk_link
    gcid, siteid, adzoneid = self.__get_tk_link_s1(auctionid, tb_token, pvid)
  File "/app/libs/alimama.py", line 324, in __get_tk_link_s1
    gcid = rj['data']['otherList'][0]['gcid']
KeyError: 'data'
