### ISSUE TITLE
微信不能登录成功。。

### ISSUE THREAD

**Issue by micezhao** [xsren/wx_taobao_fanli#32]
2018-12-07 09:10:09,084 check_login[line:112] [DEBUG]: checking login status.....
2018-12-07 09:10:09,295 login[line:249] [DEBUG]: 淘宝已经登录 不需要再次登录
Getting uuid of QR code.
Downloading QR code.
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    run()
  File "main.py", line 19, in run
    wb.run()
  File "/app/libs/wx_bot.py", line 155, in run
    itchat.auto_login(hotReload=True)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 49, in login
    picDir=picDir, qrCallback=qrCallback)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 123, in get_QR
    utils.print_qr(picDir)
  File "/usr/local/lib/python2.7/dist-packages/itchat/utils.py", line 83, in print_qr
    subprocess.call(['xdg-open', fileDir])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by pinootto** [comment]
You can try with:
itchat.auto_login(enableCmdQR=True)

See this other issue: https://github.com/littlecodersh/ItChat/issues/490
