### ISSUE TITLE
不管什么商品，都回复没有。

### ISSUE THREAD

**Issue by xiashao** [xsren/wx_taobao_fanli#33]
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\54370\Desktop\wx_taobao_fanli-master\libs\wx_bot.py", line 50, in check_if_is_tb_link
    url = re.search(r'http://.* \)', msg.text).group().replace(u' )', '')
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\54370\Desktop\wx_taobao_fanli-master\libs\wx_bot.py", line 53, in check_if_is_tb_link
    taokouling = re.search(r'€.*?€', msg.text).group()
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\54370\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'gbk' codec can't encode character '\u20ac' in position 644: illegal multibyte sequence
Call stack:
  File "C:\Users\54370\Desktop\wx_taobao_fanli-master\main.py", line 23, in <module>
    run()
  File "C:\Users\54370\Desktop\wx_taobao_fanli-master\main.py", line 19, in run
    wb.run()
  File "C:\Users\54370\Desktop\wx_taobao_fanli-master\libs\wx_bot.py", line 158, in run
    itchat.run(True)
  File "C:\Users\54370\AppData\Local\Programs\Python\Python37\lib\site-packages\itchat\components\register.py", line 99, in run
    reply_fn()
  File "C:\Users\54370\AppData\Local\Programs\Python\Python37\lib\site-packages\itchat\components\register.py", line 91, in reply_fn
    self.configured_reply()
  File "C:\Users\54370\AppData\Local\Programs\Python\Python37\lib\site-packages\itchat\components\register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "C:\Users\54370\Desktop\wx_taobao_fanli-master\libs\wx_bot.py", line 141, in text_reply
    check_if_is_tb_link(msg)
  File "C:\Users\54370\Desktop\wx_taobao_fanli-master\libs\wx_bot.py", line 129, in check_if_is_tb_link
    logger.warning("error:{},trace:{}".format(str(e), trace))
Message: 'error:\'NoneType\' object has no attribute \'group\',trace:Traceback (most recent call last):\n  File "C:\\Users\\54370\\Desktop\\wx_taobao_fanli-master\\libs\\wx_bot.py", line 50, in check_if_is_tb_link\n    url = re.search(r\'http://.* \\)\', msg.text).group().replace(u\' )\', \'\')\nAttributeError: \'NoneType\' object has no attribute \'group\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "C:\\Users\\54370\\Desktop\\wx_taobao_fanli-master\\libs\\wx_bot.py", line 53, in check_if_is_tb_link\n    taokouling = re.search(r\'€.*?€\', msg.text).group()\nAttributeError: \'NoneType\' object has no attribute \'group\'\n'
Arguments: ()
[0;33m2019-01-16 21:44:09,872 check_if_is_tb_link[line:129] [WARNING]: error:'NoneType' object has no attribute 'group',trace:Traceback (most recent call last):
  File "C:\Users\54370\Desktop\wx_taobao_fanli-master\libs\wx_bot.py", line 50, in check_if_is_tb_link
    url = re.search(r'http://.* \)', msg.text).group().replace(u' )', '')
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\54370\Desktop\wx_taobao_fanli-master\libs\wx_bot.py", line 53, in check_if_is_tb_link
    taokouling = re.search(r'€.*?€', msg.text).group()
AttributeError: 'NoneType' object has no attribute 'group'
[0m
Request to send a text message to @96db318c18503aa35b046ebbcbb4027bccfe03ee85a0d1becf2f7816aeaaeffe: 荷叶茶冬瓜荷叶茶叶 纯干玫瑰花茶袋泡花草茶包组合天然决明正品子
-----------------
该宝贝暂时没有找到内部返利通道！亲您可以换个宝贝试试，也可以联系我们群内管理员帮着寻找有返现的类似商品
```
就是这样，我该怎么办

**Comment by dowell123** [comment]
我的能，但是cookie会过期
