### ISSUE TITLE
cookies问题，登录问题

### ISSUE THREAD

**Issue by openxbmc** [xsren/wx_taobao_fanli#39]
一开始提示"请更新最新的cookie到cookies_taobao.txt文件中！！！"后来发现alimama.py文件获取cookies的文件名不是cookies_taobao,txt，而是cookies.txt.修改后执行python main.py命令后提示如下：
error cookie
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from libs.wx_bot import WxBot
  File "C:\Users\Yang\Desktop\wx_taobao_fanli-master\libs\wx_bot.py", line 29, in <module>
    al = Alimama(logger)
  File "C:\Users\Yang\Desktop\wx_taobao_fanli-master\libs\alimama.py", line 45, in __init__
    self.load_cookies()
  File "C:\Users\Yang\Desktop\wx_taobao_fanli-master\libs\alimama.py", line 99, in load_cookies
    self.set_cookies(c_str)
  File "C:\Users\Yang\Desktop\wx_taobao_fanli-master\libs\alimama.py", line 106, in set_cookies
    for k,v in cookies.items():
UnboundLocalError: local variable 'cookies' referenced before assignment

**Comment by HailPHP** [comment]
你的解决了么？运行环境是什么？

**Comment by openxbmc** [comment]
> 你的解决了么？运行环境是什么？

没有解决，目前等待高手指点

**Comment by jtning** [comment]
俺也一样

**Comment by jtning** [comment]
四个月过去了 请问问题解决了吗

**Comment by ToJ112** [comment]
请问问题解决了吗 遇见了同样的问题

**Comment by HailPHP** [comment]
> 请问问题解决了吗 遇见了同样的问题
没解决，根本实现不了自动登录 了现在

**Comment by biaobiaocai** [comment]
无法登陆，提示“请更新最新的cookie到cookies_taobao.txt文件中”，登陆阿里旺旺也不行

**Comment by HailPHP** [comment]
> 无法登陆，提示“请更新最新的cookie到cookies_taobao.txt文件中”，登陆阿里旺旺也不行

需要自己手动把cookies存到文件里

**Comment by biaobiaocai** [comment]
> > 无法登陆，提示“请更新最新的cookie到cookies_taobao.txt文件中”，登陆阿里旺旺也不行
> 
> 需要自己手动把cookies存到文件里

现在的版本好像看不到cookies了，按楼主的图也找不到，登陆阿里旺旺也不行。不知道您是怎么处理这个问题的？是在哪里找到cookies的？

**Comment by HailPHP** [comment]
> > > 无法登陆，提示“请更新最新的cookie到cookies_taobao.txt文件中”，登陆阿里旺旺也不行
> > 
> > 
> > 需要自己手动把cookies存到文件里
> 
> 现在的版本好像看不到cookies了，按楼主的图也找不到，登陆阿里旺旺也不行。不知道您是怎么处理这个问题的？是在哪里找到cookies的？


> > > 无法登陆，提示“请更新最新的cookie到cookies_taobao.txt文件中”，登陆阿里旺旺也不行
> > 
> > 
> > 需要自己手动把cookies存到文件里
> 
> 现在的版本好像看不到cookies了，按楼主的图也找不到，登陆阿里旺旺也不行。不知道您是怎么处理这个问题的？是在哪里找到cookies的？

还是在控制台查看cookie,不过过期了还是用不了的，我都已经放弃了

**Comment by jackforlit** [comment]
唉，解决error cookie也没用了。
itchat由于微信网页端没法用登录了。
